export const ICON_BY_TIPO: Record<string, string> = {
  SALUDO_OTRO: "mdi:hand-wave",
  FUERA_DE_ALCANCE_TECNICO: "mdi:alert-circle-outline",
  SOLICITUD_NO_PERMITIDA: "mdi:cancel",
  REQUIERE_CONTEXTO: "mdi:help-circle-outline",
  PASO_A_PASO: "mdi:format-list-numbered",
  INTERPRETACION_RESULTADO: "mdi:chart-box-outline",
  CONSULTA_NORMATIVA_NEGOCIO: "mdi:gavel",
  ASESORIA_PERSONALIZADA: "mdi:account-tie",
  ERROR_TECNICO: "mdi:bug-outline",
  ERROR_CONFIGURACION: "mdi:cog-outline",
  ERROR_ACCESO: "mdi:lock-alert-outline",
  ERROR_DIAN: "mdi:file-document-alert-outline",
  COMERCIAL: "mdi:cash-multiple",
  GENERAL: "mdi:robot-outline",
  TDCONSULTA: "mdi:tag-multiple-outline",
  EXTRACTOR_CONSULTAS: "mdi:filter-outline",
  CLASIFICADOR_MODULO: "mdi:view-module-outline",
};
